spring:
  application:
    name: demo


spring-doc:
  swagger-ui:
    path: /api  # swagger-ui ?? ??? ?? ??, ?? ??? ???? http://localhost:8080/swagger-ui/index.html? ????? ?.
    groups-order: DESC # path, query, body, response ??? ??
    tags-sorter: alpha # ??? ??? ??? ??
    operations-sorter: method  # delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??
  paths-to-match:
    - /** # swagger-ui? ??? api? ????? ??